"""update tables

Revision ID: 40661a7034ad
Revises: c99e5dba3f6a
Create Date: 2024-05-19 00:39:00.030787

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40661a7034ad"
down_revision: Union[str, None] = "c99e5dba3f6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "task",
    sa.Column("is_completed", sa.Boolean(), nullable=False, comment="完了フラグ"),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("task", "is_completed")
  # ### end Alembic commands ###
